inheriting from std::exception class
